### ISSUE TITLE
composer update error 

### ISSUE THREAD

**Issue by tomoat** [fancyecommerce/yii2_fecshop_app_advanced#11]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-mongodb 2.1.7 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - fancyecommerce/fecshop 1.4.4.0 requires yiisoft/yii2-mongodb ~2.1.7 -> satisfiable by yiisoft/yii2-mongodb[2.1.7].
    - Installation request for fancyecommerce/fecshop >=1.4.4.0 -> satisfiable by fancyecommerce/fecshop[1.4.4.0].

**Comment by lichunqiang** [comment]
you should install the `mongdb` extension firstly.

if just install directly, you can try add option: `--ignore-platform-reqs`
