### ISSUE TITLE
关于判断是否是https的代码

### ISSUE THREAD

**Issue by wenjianwzz** [fancyecommerce/yii2_fecshop_app_advanced#12]
看到代码中$http = ($_SERVER['SERVER_PORT'] == 443) ? 'https' : 'http';来判断是否是https, 这样是否有点草率. 也可以使用$_SERVER['HTTPS']等信息来判断, 此处望斟酌.

**Comment by fancyecommerce** [comment]
现在时间有点久远了，当时查了一种方法，我记得是通过`$_SERVER['HTTPS']`,好像有一些问题（忘记是代理，还是什么原因了）

后来使用了通过端口443来判断的，当时事情比较多，就这样设定了

多谢你的issue，此处确实有点不妥，不过大众化的基本都是443来判断

如果环境特殊，不满足条件，可以改一下index.php的代码

这里先这样，如果您有更好的方式可以继续提一下，多谢issue
