### ISSUE TITLE
composer update失败 

### ISSUE THREAD

**Issue by ywmm3951** [fancyecommerce/yii2_fecshop_app_advanced#4]
失败原因是yiisoft/yii2-mongodb 更新失败，可不可以不强制安装这个模块，因为并不是必须的。

**Comment by fancyecommerce** [comment]
fecshop必须安装mongodb，安装失败的原因是你没有安装php mongodb扩展，下载地址为：
https://pecl.php.net/package/mongodb
mongodb安装教程：http://www.fancyecommerce.com/2016/05/03/yii2-mongodb%E7%9A%84%E5%AE%89%E8%A3%85%E5%92%8C%E9%85%8D%E7%BD%AE-mongo/

**Comment by ywmm3951** [comment]
请问目前项目进展到哪一步了？

**Comment by fancyecommerce** [comment]
五月份出正式版
